version: "3.7"

services:
  nwaku:
    image: ${NWAKU_IMAGE:-quay.io/wakuorg/nwaku-pr:3807}
    restart: on-failure
    ports:
      - 30304:30304/tcp
      - 30304:30304/udp
      - 127.0.0.1:8003:8003
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
        compress: "true"
        tag: "nwaku-{{.ID}}"
    environment:
      NODEKEY: ${NODEKEY}
      KAD_BOOTSTRAP_NODES: ${KAD_BOOTSTRAP_NODES}
      CLUSTER_ID: ${CLUSTER_ID}
      MIX_DISABLE_COVER_TRAFFIC: ${MIX_DISABLE_COVER_TRAFFIC}
      NUM_SHARDS_IN_NETWORK: ${NUM_SHARDS_IN_NETWORK}
      SHARD: ${SHARD}
      TCP_PORT: ${TCP_PORT}
      METRICS_PORT: ${METRICS_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      MAX_CONNECTIONS: ${MAX_CONNECTIONS}
      EXTRA_ARGS: ${EXTRA_ARGS}
    volumes:
      - ./run_node.sh:/opt/run_node.sh:Z
      - ./data:/data
    working_dir: /data
    entrypoint: sh
    command:
      - /opt/run_node.sh
